name: Lint Actions
on:
  workflow_call:
    inputs:
      reporter:
        required: true
        type: string
    secrets:
      gh_token:
        required: true

jobs:
  lint-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint Github Actions
        uses: reviewdog/action-actionlint@v1.62.0
        with:
          github_token: ${{ secrets.gh_token }}
          reporter: ${{ inputs.reporter }}
          fail_on_error: true
          level: info
