name: Lint Actions (Review)
on:
  push:
    branches:
      - main

jobs:
  lint:
    uses: seamuslowry/workflows/.github/workflows/lint_actions.yml@feature/lint_on_pr_and_push
    with:
      reporter: local
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
