name: Code Quality
on:
  workflow_call:
    inputs:
      python-version:
        required: false
        default: '3.12'
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    name: PyLint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - run: pip install --upgrade pip
      - run: pip install '.[lint]'
      - run: |
          readarray -t py_files < <(git ls-files '*.py')
          pylint "${py_files[@]}"
      - run: pyright
