name: Lint Actions
on: push

jobs:
  lint-yaml:
    runs-on: ubuntu-latest
    name: Lint YAML
    steps:
      - uses: actions/checkout@v3
      - uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .github/workflows/

  lint-actions:
    runs-on: ubuntu-latest
    name: List Github Actions
    steps:
      - uses: actions/checkout@v3
      - name: Check workflow files
        uses: docker://rhysd/actionlint:latest
        with:
          args: -color
