name: Lint Actions (Review)
on:
  push:
    branches:
      - main

jobs:
  lint:
    uses: seamuslowry/workflows/.github/workflows/lint_actions.yml@main
    with:
      reporter: github-che
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
