name: Tag

on:
  workflow_call:
    outputs:
      tag:
        description: "The generated tag"
        value: ${{ jobs.tag.outputs.tag }}
    secrets:
      gh_token:
        required: true
  push:
    branches:
      - main
      - chore/tag

jobs:
  tag:
    name: Tag Version
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag-version.outputs.tag }}
    steps:
      - id: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - id: tag-version
        uses: anothrNick/github-tag-action@1.52.0
        env:
          GITHUB_TOKEN: ${{ secrets.gh_token || secrets.GITHUB_TOKEN }}
          WITH_V: false
          DEFAULT_BUMP: patch
