name: Tag

on:
  workflow_call:
    inputs:
      custom-tag:
        required: false
        type: string
      dry-run:
        required: false
        default: false
        type: boolean
      with-v:
        required: false
        default: false
        type: boolean

    outputs:
      tag:
        description: "The generated tag"
        value: ${{ jobs.tag.outputs.tag }}
    secrets:
      gh_token:
        required: true
  push:
    branches:
      - main

jobs:
  tag:
    name: Tag Version
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag-version.outputs.tag }}
    steps:
      - id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"
      - id: tag-version
        uses: anothrNick/github-tag-action@1.57.0
        env:
          GITHUB_TOKEN: ${{ secrets.gh_token || secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: ${{ inputs.custom-tag }}
          WITH_V: ${{ inputs.with-v }}
          DEFAULT_BUMP: minor
          DRY_RUN: ${{ inputs.dry-run }}
