name: Test and Check Coverage
on:
  workflow_call:
    inputs:
      min-coverage:
        required: false
        default: 100
        type: number
      python-version:
        required: false
        default: '3.10'
        type: string
      compose-file:
        required: false
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    name: PyTest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - if: (inputs.compose-file != '')
        run: docker compose -f "${{ inputs.compose-file }}" up -d --build
      - run: pip install --upgrade pip
      - run: pip install '.[test]'
      - run: coverage run --branch --source=. -m pytest tests
      - run: coverage report --fail-under=${{ inputs.min-coverage }}
      - if: always() && (inputs.compose-file != '')
        run: docker compose -f "${{ inputs.compose-file }}" down --volumes
